### ISSUE TITLE
improve code editor

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/angry-coders-game#13]
- use larger font size
 - use a font like **Fira Mono** maybe. Current one not so _cool_ 😆

**Comment by 0xnmn** [comment]
What about a UI change like : https://codingblocks.com/tic-tac-toe/

Well both need editor changes too.

**Comment by prateek27** [comment]
@hereisnaman you can give tic-tac-toe like background UI to angry coders as well. This will also avoid scaling issues to full screen :) ! you can just center the game.
