### ISSUE TITLE
fix y co-ordinates in level0.json

### ISSUE THREAD

**Issue by asutosh7hota** [coding-blocks/angry-coders-game#14]
The coordinates of the boxes are all set to 400

**Comment by prateek27** [comment]
@asutosh7hota all the blocks fall from the same point, that's why the initial coordinates are same.

**Comment by asutosh7hota** [comment]
@prateek27  Then I guess this issue should be closed here :)

**Comment by championswimmer** [comment]
i've taken @asutosh7hota PR, because it prevents boxes falling too hard and getting displaced.

**Comment by asutosh7hota** [comment]
:+1:
