### ISSUE TITLE
make title consistent: "Angry" not "Happy"

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/angry-coders-game#20]
- [ ] change HTML title tag
- [ ] change in game graphic

<img width="778" alt="happy_coders_-_the_coders_game" src="https://cloud.githubusercontent.com/assets/1327050/26510130/71df7350-4279-11e7-81dc-2fcc9f204d1c.png">

**Comment by abhishek97** [comment]
`Make Coders Angry Again` :D #21

**Comment by abhishek97** [comment]
@championswimmer @prateek27 There are already many PR which are exactly identical, please close this.
