### ISSUE TITLE
allow going to next level  iff top block falls and other blocks do not fall

### ISSUE THREAD

**Issue by championswimmer** [coding-blocks/angry-coders-game#6]

**Comment by championswimmer** [comment]
iff == if and only if

**Comment by asutosh7hota** [comment]
I wanted some more explanation in the problem statement,
1. I have to click reset level every time I kick the ball, might be successful or unsuccessful.(The chances are also not being updated, they are updated only after hitting reset level) 
2. The ball travels infinitely if it falls out of the ground, should I add a condition here too?

Should we change the code such that when the bird falls, it would go to the next level without clicking the reset button?

**Comment by prateek27** [comment]
1. Make changes after every unsuccessful try, the ball should stop after moving some distance and level should be reset. When only top block falls - next level should start.
2. Yes ball shouldn't travel to infinity. Make required changes.

Bounty is 200 points for above changes.

**Comment by asutosh7hota** [comment]
@prateek27  The infinite ball and box fall is fixed however I would like to know your insights on the proper approach to this. I hope when the ball collides with just the top block, you win the game.

the other boundary conditions must be:

- Both the ball and top block can fall of the floor.

- The ball remains on the floor and top block falls 

- the top block remains on the floor after being hit and the ball falls down the floor.

Are there any other boundary conditions that I must take into consideration?

**Comment by Vatsalgarg1617** [comment]
@championswimmer  sir I would like to contribute on this project. Is this is resolved ?

**Comment by vibhorgupta-gh** [comment]
@championswimmer is this still active?

**Comment by prajwalkpandey** [comment]
i need some explanation...
by top block shoul fall but not others...
Does it mean top block should fall infinitely and others can fall on the ground...
or top should fall infintely and others cont even fall to the ground level....

and to win is it necessary that ball wont fall infintely even when top block fell
